services:
  api:
    image: rameez49/solar-panel-api:latest
    container_name: solar-panel-api
    ports:
      - "8000:8000"

  streamlit:
    image: rameez49/solar-panel-ui:latest
    container_name: solar-panel-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000/predict