version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: rameez49/solar-panel-api:latest
    ports:
      - "8000:8000"
    container_name: solar-panel-api

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    image: rameez49/solar-panel-ui:latest
    ports:
      - "8501:8501"
    container_name: solar-panel-ui
    depends_on:
      - api
    environment:
      API_URL: http://api:8000/predict